include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_CONTACT yamschikovzs@student.bmstu.ru)
set(CPACK_PACKAGE_NAME "solver")
set(CPACK_PACKAGE_VERSION_MAJOR ${SOLVER_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${SOLVER_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${SOLVER_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION_TWEAK ${SOLVER_VERSION_TWEAK})
set(CPACK_PACKAGE_VERSION "${SOLVER_VERSION}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ application for solving equations")

set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_SOURCE_DIR}/../DESCRIPTION")
if(NOT CPACK_GENERATOR MATCHES "WIX")
  set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/../LICENSE")
endif()
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/../README.md")

set(CPACK_RPM_PACKAGE_NAME "solver")
set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")
set(CPACK_RPM_CHANGELOG_FILE "${CMAKE_SOURCE_DIR}/../ChangeLog.md")
set(CPACK_RPM_PACKAGE_RELEASE 1)

set(CPACK_DEBIAN_PACKAGE_NAME "solver")
set(CPACK_DEBIAN_PACKAGE_PREDEPENDS "cmake >= 3.0")
set(CPACK_DEBIAN_PACKAGE_RELEASE 1)

set(CPACK_WIX_PRODUCT_GUID "F9C8E4B0-3A2D-4F1E-9B8C-7D6A5E4F3C2B")
set(CPACK_WIX_UPGRADE_GUID "A1B2C3D4-E5F6-7890-ABCD-EF1234567890")
set(CPACK_WIX_PRODUCT_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.rtf")

set(CPACK_DMG_VOLUME_NAME "solver")

include(CPack)
